polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #changed to generic views
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
    #basic views
    
    # /polls/
    #path('', views.index, name='index'),
    
    # ex.: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    
    # ex.: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import include, path
from pollsite.views import HomePageView
#from django.views.generic import RedirectView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('polls/', include('polls.urls')),
    path('twitter/', include('twitter.urls')),
    path('admin/', admin.site.urls),
]

twitter/urls.py
from django.urls import path

from . import views

app_name = 'twitter'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

twitter/models.py
from django.db import models

class Tweet(models.Model):
    tweet_text = models.CharField(max_length=200)
    tweet_author = models.CharField(max_length=200)
    def __str__(self):
        return self.tweet_text
    def __author__(self):
        return self.tweet_author

polls/views.py
from django.http import HttpResponseRedirect
#from django.http import HttpResponse
#from django.http import Http404
from django.shortcuts import get_object_or_404, render
#from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

#generic, class-based views
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set
        to be published in the future."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:15]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        # Exclude future questions
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        
        
#basic views 

# def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:8]
    # #template = loader.get_template('polls/index.html')
    # context = {
        # 'latest_question_list': latest_question_list,
    # }
    # return render(request, 'polls/index.html', context)
    
# def detail(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/detail.html', {'question': question})
    # #return HttpResponse("You're looking at question %s." % question_id)
    
# def results(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/results.html', {'question': question})

pollsite/views.py
from django.views.generic.base import TemplateView

class HomePageView(TemplateView):

    template_name = "pollsite/home.html"

twitter/views.py
from django.shortcuts import render
from django.http import HttpResponse
#from django.views import generic
import tweepy, os

from .models import Tweet

consumer_key = os.environ["POLLSITE_TWITTER_CONSUMER_KEY"]
consumer_secret = os.environ["POLLSITE_TWITTER_CONSUMER_SECRET"]
access_token = os.environ["POLLSITE_TWITTER_ACCESS_TOKEN"]
access_token_secret = os.environ["POLLSITE_TWITTER_ACCESS_TOKEN_SECRET"]

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
tweet_list = []
    
statuses = api.search('#django', count=10)
for status in statuses:
    tweet_list.append(status.user.name + ': ' + status.text)
    
print(tweet_list)
    
def index(request):
    context = {'tweet_list': tweet_list}
    return render(request, 'twitter/index.html', context)

polls/templates/polls/detail.html
{% extends 'pollsite/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="grid-container grid-head">
    <div class="grid-item"><h1>{{ question.question_text }}</h1></div>
</div>



<div class="grid-container">
    {% if error_message %}
    <div class="grid-item"><p><strong>{{ error_message }}</strong></p></div>
    {% endif %}
    <div class="grid-item">
        <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <br>
        <input type="submit" value="Vote" style="background-color: #3fff33"/>
        </form>
    </div>
</div>

{% endblock %}

polls/templates/polls/index.html
{% extends 'pollsite/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="grid-container grid-head">
    <div class="grid-item"><h1>Questions up for voting</h1></div>
</div>

<div class="grid-container">
    {% if latest_question_list %}
    {% for question in latest_question_list %}
    <div class="grid-item">
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </div>
    {% endfor %}
    {% else %}
    <div class="grid-item"><p>No polls are available.</p></div>
    {% endif %}
</div>

{% endblock %}

polls/templates/polls/results.html
{% extends 'pollsite/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="grid-container grid-head">
    <div class="grid-item"><h1>{{ question.question_text }}</h1></div>
</div>

<div class="grid-container">
    <div class="grid-item">
        
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        
    </div>
    <div class="grid-item">
        <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    </div>
</div>

{% endblock %}

pollsite/templates/pollsite/base.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'polls/base.css' %}">

<div class="header">
    <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn">&#x2630;</button>
        <div id="myDropdown" class="dropdown-content">
            <a href="{% url 'home' %}">home</a>
            <a href="{% url 'polls:index' %}">voting app</a>
            <a href="{% url 'twitter:index' %}">twitter search app</a>
            <a href="http://pluttik.github.io">my CSS/Javascript site</a>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<script src="{% static 'polls/base.js' %}"></script>

pollsite/templates/pollsite/home.html
{% extends 'pollsite/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="grid-container grid-head">
    <div class="grid-item"><h1>Welcome to my Django site</h1></div>
</div>

<div class="grid-container">
    <div class="grid-item">
        <p>Click <a href="{% url 'polls:index' %}">here</a> to view the voting app</p></div>
    <div class="grid-item">
        <p>Click <a href="{% url 'twitter:index' %}">here</a> to see recent tweets about Django</p></div>
</div>

{% endblock %}

twitter/templates/twitter/index.html
{% extends 'pollsite/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<div class="grid-container grid-head">
    <div class="grid-item"><h1>Twitter search</h1></div>
</div>

<div class="grid-container">
    <div class="grid-item">
        <p><b>The latest tweets about Django</b></p>
    </div>
    {% if tweet_list %}
    {% for tweet in tweet_list %}
    <div class="grid-item">
        <p>{{ tweet }}</p>
        <p>{{ tweet.tweet_text }}</p>
    </div>
    {% endfor %}
    {% else %}
    <div class="grid-item"><p>No tweets are available.</p></div>
    {% endif %}
</div>

{% endblock %}